"""TLSH locality-sensitive hashing for persona activation vectors.

Persona vectors generated by `generate_vec.py` are float32 tensors shaped
`[layers, hidden_dim]`. This module turns each layer's vector into a TLSH
digest, and exposes the standard TLSH diff (lower = more similar).

Floats are first run through `encoding.encode_vector`, which produces a
distance-preserving 2-byte-per-activation stream: `(bucket_idx, neighbor_idx)`.
That keeps TLSH n-gram statistics correlated with activation distance,
unlike raw float32 bytes where small numeric changes can flip whole bytes.

The `tlsh` C extension is vendored under `persona_vectors/vendor/tlsh`; build
and install it with:

    cd persona_vectors/vendor/tlsh/py_ext && pip install .
"""
from __future__ import annotations

from pathlib import Path
from typing import Iterable

import numpy as np
import torch

from encoding import ArrayLike, encode_layers, encode_vector

try:
    import tlsh as _tlsh
except ImportError as e:
    raise ImportError(
        "The `tlsh` extension is not installed. Build the vendored copy with: "
        "`cd persona_vectors/vendor/tlsh/py_ext && pip install .`"
    ) from e


def hash_vector(vector: ArrayLike, edges: ArrayLike) -> str:
    """TLSH digest of a single 1-D activation vector under the given edges.

    Returns an empty string if TLSH refuses the input (too short or too
    uniform); callers should treat that as "no digest".
    """
    return _tlsh.hash(encode_vector(vector, edges))


def hash_layers(vectors: ArrayLike, edges: ArrayLike) -> list[str]:
    """One TLSH digest per layer for a `[layers, hidden_dim]` tensor."""
    return [_tlsh.hash(buf) for buf in encode_layers(vectors, edges)]


def hash_persona_file(path: str | Path, edges: ArrayLike) -> list[str]:
    """Load a saved persona vector (.pt) and TLSH-hash each layer."""
    tensor = torch.load(path, map_location="cpu")
    if not isinstance(tensor, torch.Tensor):
        raise TypeError(f"{path}: expected torch.Tensor, got {type(tensor).__name__}")
    return hash_layers(tensor, edges)


def diff(digest_a: str, digest_b: str) -> int:
    """TLSH distance between two digests (0 = identical, larger = more different)."""
    return _tlsh.diff(digest_a, digest_b)


def pairwise_diff(digests: Iterable[str]) -> np.ndarray:
    """Symmetric NxN matrix of pairwise TLSH distances."""
    digests = list(digests)
    n = len(digests)
    matrix = np.zeros((n, n), dtype=np.int32)
    for i in range(n):
        for j in range(i + 1, n):
            d = diff(digests[i], digests[j])
            matrix[i, j] = d
            matrix[j, i] = d
    return matrix


if __name__ == "__main__":
    import argparse

    from encoding import linear_edges, quantile_edges

    parser = argparse.ArgumentParser(description="TLSH-hash a saved persona vector file.")
    parser.add_argument("path", help="path to a .pt file produced by generate_vec.py")
    parser.add_argument(
        "--edges",
        choices=("linear", "quantile"),
        default="quantile",
        help="how to derive bucket edges (linear uses [-6, 6], quantile uses the file's own values).",
    )
    args = parser.parse_args()

    tensor = torch.load(args.path, map_location="cpu")
    if args.edges == "linear":
        edges = linear_edges(-6.0, 6.0)
    else:
        edges = quantile_edges(tensor)

    for layer, digest in enumerate(hash_layers(tensor, edges)):
        print(f"layer {layer:3d}: {digest or '<no-digest>'}")
